# 1. Обработка исключений

## 1.1 Конструкция try..catch..finally

- при использовании блока try..catch..finally, выполняются все инструкции в блоке try. Если исключений не возникло, то выполняется блока finally
- если же в блоке try возникло исключение, то порядок выполнения останавливается и среда CLR начинает искать соответствующий блок catch для обработки исключения. После выполнения блока catch выполняется блок finally
- если при возникновении исключения блок catch не найдет, программа аварийно завершает свое выполнение

```csharp
// Result: catch -> finally

try
{
    var x = 5;
    var y = 0;
    var result = x / y;
}
catch
{
    Console.WriteLine("catch");
}
finally
{
    Console.WriteLine("finally");
}
```

- при наличии блока catch можно опустить блок finally. Также и наоборот

## 1.2 Обработка исключений и условные конструкции

- С точки зрения производительности использование блоков try..catch более накладно, чем применение условных конструкций.

# 2. Блок catch и фильтры исключений

## 2.1 Определение блока catch

- переменную ex можно опустить
- в переменную ex помещается информация о вызванном исключении

```csharp
try
{

}
catch
{
    // обрабатывает любое исключение
}
catch (OverflowException ex)
{
    // обрабатывает исключение по типу
}
```

## 2.2 Фильтры исключений

- позволяют обработать исключение в зависимости от определенных условий

```csharp
var x = 5;
var y = 0;

try
{
    var result = x / y;
}
catch (DivideByZeroException) when (y == 0)
{
    Console.WriteLine("catch");
}
catch (DivideByZeroException)
{
    Console.WriteLine("catch");
}
```

# 3. Типы исключений. Класс Exception

- базовый класс всех исключений Exception
- также есть более специализированные типы исключений

Свойства класса:
- InnerException - информация об исключении, которое послужило причиной текущего исключения
- Message - сообщение об исключении
- Source - хранит имя объекта или сборки, которое вызвало исключение
- StackTrace - представление стека вызовов, которое привело к исключению
- TargetSite - возвращает метод, в котором и было вызвано исключение

# 4. Генерация исключения и оператор throw

- оператор `throw new` предназначен, чтобы вручную генерировать исключения

```csharp
var x = 11;
var y = 6;

try
{
    var result = x / y;
    if (result != 0)
    {
        throw new Exception("Result isn't 0");
    }
}
catch (Exception ex)
{
    Console.WriteLine(ex.Message);
}
```

- также имеется другая сторона оператора `throw`, где после данного оператора не указывается объект исключения
- тогда такой оператор можно использовать только в блоке catch
- такой вид оператора throw передает обработку исключения внешнему блоку catch

```csharp
try
{
    var x = 11;
    var y = 6;

    try
    {
        var result = x / y;
        if (result != 0)
        {
            throw new Exception("Result isn't 0");
        }
    }
    catch (Exception ex)
    {
        throw;
    }
}
catch
{
    Console.WriteLine("Catch - 2");
}
```

# 5. Создание классов исключений

- если не устраивают встроенные типы исключений, мы можем создать свой
- необязательно наследоваться от Exception, можно от любого другого, который производный от Exception

```csharp
class PersonException : Exception
{
    public PersonException(string message)
        : base(message) { }
}
```
